# Generated by Django 4.2.6 on 2023-11-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture_url',
            field=models.CharField(default='https://cdn3.emoji.gg/emojis/6392-gigachad.png', max_length=200),
        ),
    ]
