# Generated by Django 4.2.6 on 2023-10-24 20:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("threads", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thread",
            name="author",
        ),
    ]
