# Generated by Django 4.2.6 on 2023-10-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("threads", "0002_remove_thread_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
