# Generated by Django 4.2.6 on 2023-11-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='content_visibility',
            field=models.IntegerField(choices=[(1, 'Visible to everyone'), (2, 'Visible to registered users'), (3, 'Visible to group members')], default=1),
        ),
    ]
