# Generated by Django 4.2.6 on 2023-11-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='requested_for_moderator',
            field=models.ManyToManyField(related_name='requested_for_moderator', to='users.profile'),
        ),
    ]
