# Generated by Django 4.2.6 on 2023-11-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_profile_picture_url'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='content_visibility',
            field=models.IntegerField(choices=[(1, 'Visible to everyone'), (2, 'Visible to registered users'), (3, 'Visible to group members')], default=1),
        ),



        migrations.AlterField(
            model_name='group',
            name='image_url',
            field=models.CharField(default='https://www.poszetka.com/data/include/img/news/1650028664.jpg', max_length=200),
        ),
    ]
