# Generated by Django 4.2.6 on 2023-11-25 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_visibility'),
        ('groups', '0002_group_content_visibility_group_moderators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='members', to='users.profile'),
        ),
        migrations.AddField(
            model_name='group',
            name='requested_to_join',
            field=models.ManyToManyField(related_name='requested_to_join', to='users.profile'),
        ),
    ]
