# Generated by Django 4.2.6 on 2023-11-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_members_group_requested_to_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='image_url',
            field=models.CharField(default='https://www.poszetka.com/data/include/img/news/1650028664.jpg', max_length=200),
        ),
    ]
