# Generated by Django 4.2.5 on 2023-11-27 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0002_group_content_visibility_group_members_and_more"),
        ("groups", "0004_alter_group_image_url"),
    ]

    operations = []
